### ISSUE TITLE
[Feature Description] Discuss and suggest features

### ISSUE THREAD

**Issue by raveesh-me** [DSCHeritage/DevFestKolkata#1]
Discuss the needed features under this thread

**Comment by raunak111** [comment]
Let's not have an app bar, coz it might confuse users whether they can swipe, or if we have an app bar we might have to do it WhatsApp style with tap bars. What do you say?

**Comment by theveryharsh** [comment]
WhatsApp style is too cliched, I propose the Google's material design better, furthermore when this is a Google event.
Google's material design is basically a bottom tap bar view like the Google Photos android app has.
Views?

**Comment by raunak111** [comment]
![screenshot](https://user-images.githubusercontent.com/37953138/46367795-33241280-c69c-11e8-846f-2b65d9be8dfd.png)

As we have more than 5 screens to implement, either we have to choose the good old navigation drawer or don't have an app bar

**Comment by raveesh-me** [comment]
> Let's not have an app bar, coz it might confuse users whether they can swipe, or if we have an app bar we might have to do it WhatsApp style with tap bars. What do you say?

Adding the AppBar was just to show you how to contribute. Contact @28JayG about the design wireframe, he has the whole thing, we are building our own interaction models

**Comment by raveesh-me** [comment]
Whatsapp Implements Google Material Design to the letter.
Material Design is mistaken to be a design language where it is more of a philosophy to base your language on.

**Comment by 28JayG** [comment]
Its better not to have appBar as our design is quite different than any other app that comes to my mind. Having Tabs might distract the user from the vertical track gesture which is the signature of our app
