### ISSUE TITLE
[Design]Make an Announcement Screen

### ISSUE THREAD

**Issue by raveesh-me** [DSCHeritage/DevFestKolkata#11]
We need to wireframe an Announcement Screen and figure out what individual announcements would look like

**Comment by raunak111** [comment]
I am thinking of having a bottom navigation bar for following contexts #general announcement #quicklinks #speaker announcement in the announcement screen, need approval or suggestions

**Comment by raveesh-me** [comment]
we are using bottom nav for the main stuff, so it'll overlap if you do it for a single screen.
i am not in favor
