### ISSUE TITLE
Index Calculator for left side is buggy

### ISSUE THREAD

**Issue by raveesh-me** [DSCHeritage/DevFestKolkata#30]
https://github.com/DSCHeritage/DevFestKolkata/blob/80cac5962e6792d3b32eb22ae92f33e8dbb450fd/lib/screens/session_detail_screen/layers/selector_layer/selector_layer.dart#L23

Need to change _rightSessions.legth to _leftSessions.length

**Comment by raveesh-me** [comment]
@28JayG @jackfrost13 want to take a try at this?

**Comment by 28JayG** [comment]
On it

**Comment by raveesh-me** [comment]
this issue was solved long ago
