### ISSUE TITLE
Make the static organisers details screen

### ISSUE THREAD

**Issue by raveesh-me** [DSCHeritage/DevFestKolkata#9]
Make a static organisers details screen to highlight GDGKolkata and WTMKolkata.
Include their social media profiles in it as well, in the form of IconButtons

- [ ] Model the Organier Details

- [ ] make a StatelessWidget that takes in `OrganiserDetails` and lays them out

- [ ] In the organiers_details_screen, make a ListView and pass the organisers to the OrganierDetailsWidget and add all the organisers as children

The organisers, in this case, are GDG, WTM, Google Developers, DSC(ask Rivu da about it)

**Comment by raveesh-me** [comment]
@jackfrost13 @28JayG  one of you make the PR, and both of you hold discussions here on how to do things.

**Comment by 28JayG** [comment]
Okay on it, but what should be the other details except for social handles, name, and logo? @raveesh-me

**Comment by raveesh-me** [comment]
Name, logo, Generic Description, Unique About Kolkata chapter, and social media handles
